openapi: 3.0.0
info:
  title: TurboDocx Core API
  version: 1.0.0
  description: Core API endpoints for TurboDocx document generation and manipulation
  contact:
    name: TurboDocx Support
    email: support@turbodocx.com
    url: https://www.turbodocx.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.turbodocx.com/v1
    description: Production server
  - url: https://staging-api.turbodocx.com/v1
    description: Staging server

paths:
  /status:
    get:
      summary: Get API status
      description: Check the status of the TurboDocx API
      operationId: getStatus
      tags:
        - Health
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  version:
                    type: string
                    example: 1.0.0

  /documents:
    post:
      summary: Create a document
      description: Generate a new document from a template
      operationId: createDocument
      tags:
        - Documents
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                templateId:
                  type: string
                  description: ID of the template to use
                data:
                  type: object
                  description: Data to populate the template
                format:
                  type: string
                  enum: [docx, pdf, html]
                  default: docx
              required:
                - templateId
                - data
      responses:
        '201':
          description: Document created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  url:
                    type: string
                  status:
                    type: string
        '400':
          description: Invalid request
        '401':
          description: Unauthorized

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
