openapi: 3.0.0
info:
  title: TurboDocx Signature API
  version: 1.0.0
  description: API endpoints for digital signature operations
  contact:
    name: TurboDocx Support
    email: support@turbodocx.com
    url: https://www.turbodocx.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.turbodocx.com/v1
    description: Production server
  - url: https://staging-api.turbodocx.com/v1
    description: Staging server

paths:
  /signatures:
    post:
      summary: Create a signature request
      description: Request a digital signature for a document
      operationId: createSignatureRequest
      tags:
        - Signatures
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                documentId:
                  type: string
                  description: ID of the document to sign
                signers:
                  type: array
                  items:
                    type: object
                    properties:
                      email:
                        type: string
                        format: email
                      name:
                        type: string
                    required:
                      - email
                      - name
                message:
                  type: string
                  description: Optional message to signers
              required:
                - documentId
                - signers
      responses:
        '201':
          description: Signature request created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  status:
                    type: string
                    enum: [pending, completed, expired]
                  signers:
                    type: array
                    items:
                      type: object
                      properties:
                        email:
                          type: string
                        status:
                          type: string
                        signUrl:
                          type: string
        '400':
          description: Invalid request
        '401':
          description: Unauthorized

  /signatures/{id}:
    get:
      summary: Get signature request status
      description: Retrieve the status of a signature request
      operationId: getSignatureRequest
      tags:
        - Signatures
      security:
        - ApiKeyAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Signature request ID
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  status:
                    type: string
                  signers:
                    type: array
                    items:
                      type: object
                      properties:
                        email:
                          type: string
                        status:
                          type: string
                        signedAt:
                          type: string
                          format: date-time
        '404':
          description: Signature request not found
        '401':
          description: Unauthorized

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
